apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-retool-self-hosted-blueprints-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Retool Blueprints (GCP Marketplace)
    source:
      repo: https://github.com/tryretool/terraform-retool-self-hosted-blueprints.git
      sourceType: git
      dir: /marketplace/gcp
  ui:
    input:
      variables:
        project_id:
          name: project_id
          title: Project Id
          invisible: true
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Deployment name
        domain_name:
          name: domain_name
          title: Domain name
        region:
          name: region
          title: Region
        license_key:
          name: license_key
          title: License key
        prefix:
          name: prefix
          title: Resource name prefix
          invisible: true
        helm_release_name:
          name: helm_release_name
          title: Helm Release Name
          invisible: true
        helm_chart_repo:
          name: helm_chart_repo
          title: Helm Chart Repo
          invisible: true
        helm_chart_name:
          name: helm_chart_name
          title: Helm Chart Name
          invisible: true
        helm_chart_version:
          name: helm_chart_version
          title: Helm Chart Version
          invisible: true
        third_party_charts_repo:
          name: third_party_charts_repo
          title: Third Party Charts Repo
          invisible: true
        image_repo:
          name: image_repo
          title: Image Repo
          invisible: true
        image_tag:
          name: image_tag
          title: Image Tag
          invisible: true
        code_executor_image_repo:
          name: code_executor_image_repo
          title: Code Executor Image Repo
          invisible: true
        code_executor_image_tag:
          name: code_executor_image_tag
          title: Code Executor Image Tag
          invisible: true
        js_executor_image_repo:
          name: js_executor_image_repo
          title: Js Executor Image Repo
          invisible: true
        js_executor_image_tag:
          name: js_executor_image_tag
          title: Js Executor Image Tag
          invisible: true
        agent_sandbox_image_repo:
          name: agent_sandbox_image_repo
          title: Agent Sandbox Image Repo
          invisible: true
        agent_sandbox_image_tag:
          name: agent_sandbox_image_tag
          title: Agent Sandbox Image Tag
          invisible: true
        telemetry_image_repo:
          name: telemetry_image_repo
          title: Telemetry Image Repo
          invisible: true
        telemetry_image_tag:
          name: telemetry_image_tag
          title: Telemetry Image Tag
          invisible: true
        external_secrets_image_repo:
          name: external_secrets_image_repo
          title: External Secrets Image Repo
          invisible: true
        external_secrets_image_tag:
          name: external_secrets_image_tag
          title: External Secrets Image Tag
          invisible: true
        reloader_image_repo:
          name: reloader_image_repo
          title: Reloader Image Repo
          invisible: true
        reloader_image_tag:
          name: reloader_image_tag
          title: Reloader Image Tag
          invisible: true
        external_dns_image_repo:
          name: external_dns_image_repo
          title: External Dns Image Repo
          invisible: true
        external_dns_image_tag:
          name: external_dns_image_tag
          title: External Dns Image Tag
          invisible: true
        busybox_image_repo:
          name: busybox_image_repo
          title: Busybox Image Repo
          invisible: true
        busybox_image_tag:
          name: busybox_image_tag
          title: Busybox Image Tag
          invisible: true
        smarter_device_manager_image_repo:
          name: smarter_device_manager_image_repo
          title: Smarter Device Manager Image Repo
          invisible: true
        smarter_device_manager_image_tag:
          name: smarter_device_manager_image_tag
          title: Smarter Device Manager Image Tag
          invisible: true
